### ISSUE TITLE
XML: Article title contains plain HTML

### ISSUE THREAD

**Issue by targos** [cheminfo/molbank#2]
example:

``` xml
<article-title>
  5-(5-Bromo-2-hydroxy-3-methoxyphenyl)-7-methyl-4,5,6,7-tetrahydro[1,2,4]triazolo[1,5-
    <italic>a</italic>
  ]pyrimidin-7-ol
</article-title>
```

**Comment by lpatiny** [comment]
In the XML the value of <article-title> should contain the value of the title. Currently it can contain other XML tag which is quite confusing and prevent parsing of the title.
Could you escape this or remove it ?

``` xml
<article-title>
  5-(5-Bromo-2-hydroxy-3-methoxyphenyl)-7-methyl-4,5,6,7-tetrahydro[1,2,4]triazolo[1,5&lt;i&gt;a&lt;/i&gt; ]pyrimidin-7-ol
</article-title>
```

**Comment by ghost** [comment]
Hi Luc, we do use html tags in the XML of the articles. Can you escape the html tags once you parse the xml. We will not modify our XML structure as the title information should be preserved.

**Comment by targos** [comment]
OK we changed the way we parse the XML and this is fixed.

**Comment by ghost** [comment]
Thanks!
