### ISSUE TITLE
Missing many XML files

### ISSUE THREAD

**Issue by targos** [cheminfo/molbank#3]

**Comment by lpatiny** [comment]
For many articles we don't have XML file and therefore we don't have DOI and we can not generate the link to the original PDF.
Please could you add the missing XML ?

**Comment by ghost** [comment]
We need 3 to 4 weeks to convert all Molbank papers and have XML files available, I will keep you updated.

**Comment by ghost** [comment]
Hi Luc, we didn't got back to this project for long time, sorry for that. We now have all XML files available for Molbank journal, could you please proceed them.

**Comment by targos** [comment]
Hi. Could please send them to us? An attachment to this issue would be fine

**Comment by ghost** [comment]
Hi Targos, seems the zip file is somehow rejected by GitHub. You can download the Molbank XML files here: http://www.filedropper.com/molbankxmlfiles

**Comment by ghost** [comment]
Hi Targos, Luc, any progress on this?

**Comment by targos** [comment]
Hi. I'm sorry. I was sure that I gave feedback after the last message.

The XML files are not enough and we also need the supplementary material (especially the molfiles). I saw that the list is available in the XML but I don't know if we can turn this data into a URL to download the resource or if it's easier to have the files in the archive.
```xml
<app-group>
<app id="app1-molbank-2015-M879">
<title>Supplementary Materials</title>
<supplementary-material xmlns:xlink="http://www.w3.org/1999/xlink" id="molbank-2015-M879-s001" xlink:href="molbank-2015-M879-s001-mod.mol">
<label>Supplementary File 1</label>
</supplementary-material>
<supplementary-material xmlns:xlink="http://www.w3.org/1999/xlink" id="molbank-2015-M879-s002" xlink:href="molbank-2015-M879-s001.mol">
<label>Supplementary File 2</label>
</supplementary-material>
<supplementary-material xmlns:xlink="http://www.w3.org/1999/xlink" id="molbank-2015-M879-s003" xlink:href="molbank-2015-M879-s001.pdf">
<label>Supplementary File 3</label>
</supplementary-material>
</app>
</app-group>
```

**Comment by ghost** [comment]
Hi Targos,

No problem. All supplementary materials are available on our website:

http://www.mdpi.com/1422-8599/2015/4/M879/s1
http://www.mdpi.com/1422-8599/2015/4/M879/s2
http://www.mdpi.com/1422-8599/2015/4/M879/s3

You could basically extract the last number from the id and use it in the link, example:

http://www.mdpi.com/1422-8599/2015/4/M879/s<last_number>

**Comment by ghost** [comment]
Hi Targos, any update on this?

**Comment by targos** [comment]
I am working on it today.

I found an problem with a few articles. If I understood correctly, the URL is in the form `http://www.mdpi.com/[issn]/[volume]/[issue]/[publisher-id]`.
The article in `molbank-2003-M339.xml` has the `issue` field set to 4 but the URL is wrong with this number. The "correct" one is http://www.mdpi.com/1422-8599/2003/3/M339.
Is it a bug in the data or am I constructing the URL incorrectly?

**Comment by targos** [comment]
BTW I think your website should respond with a 404 status code when the "File not found" error is returned. For example with this URL: http://www.mdpi.com/1422-8599/2003/4/M339 the code is 200 (OK).

**Comment by targos** [comment]
There are some weird cases for the supplementary material. Take for example:
```xml
    <app id="app1-molbank-2010-M662">
        <title>Supplementary materials</title>
		<supplementary-material id="molbank-2010-M662-s003" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="molbank-2010-M662-s001.pdf">
   <label>Supplementary File 1</label>
</supplementary-material>
        <supplementary-material id="molbank-2010-M662-s001" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="molbank-2010-M662-s002-mod.mol">
   <label>Supplementary File 2</label>
</supplementary-material>
        <supplementary-material id="molbank-2010-M662-s002" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="molbank-2010-M662-s002.mol">
   <label>Supplementary File 3</label>
</supplementary-material>
    </app>
```

The id for the PDF is `molbank-2010-M662-s003` but its URL finishes with `s1`. Similar inconsistency for the mol files.
Apparently the only source of truth is the label (or the order of the elements). I will use that.

**Comment by targos** [comment]
List of 404 errors:
File not found: http://www.mdpi.com/1422-8599/2003/4/M339/s1
File not found: http://www.mdpi.com/1422-8599/2003/4/M339/s2
File not found: http://www.mdpi.com/1422-8599/2004/2/M387/s1
File not found: http://www.mdpi.com/1422-8599/2004/2/M387/s2
File not found: http://www.mdpi.com/1422-8599/2008/3/M567/s1
File not found: http://www.mdpi.com/1422-8599/2008/3/M567/s2
File not found: http://www.mdpi.com/1422-8599/2011/4/M736/s1
File not found: http://www.mdpi.com/1422-8599/2011/4/M736/s2
File not found: http://www.mdpi.com/1422-8599/2011/4/M737/s1
File not found: http://www.mdpi.com/1422-8599/2011/4/M737/s2
File not found: http://www.mdpi.com/1422-8599/2011/4/M738/s1
File not found: http://www.mdpi.com/1422-8599/2011/4/M738/s2

**Comment by ghost** [comment]
Hi Targos, Will answer all your questions within one post:

1. You're right, the url is correctly composer, however, note that on some XMLs, the article number is called "elocation-id", example: <elocation-id>M339</elocation-id>"
The given XML example seems wrong, the issue is not correct, should be 3 instead of 4. I will ask our conversion team to fix it.

There is another possibility to resolve an article URL from the XML, by using the DOI number, you can: https://dx.doi.org/<DOI>, or example http://dx.doi.org/10.3390/M339 will return you the right URL.

2. Correct, we do not return 404 error codes, we always return 200 with an HTML page showing the 404 error.

3. It seems there is also some issues with the supplementary files, will ask the conversion team to check.

4. The errors are ususally coming from wrong issues, will ask the conversion team to correct.

**Comment by ghost** [comment]
3 was corrected

**Comment by ghost** [comment]
Hi Targos,

Any progress with this? When can we expect to have a test version to be integrated with our Molbank Journal?

**Comment by targos** [comment]
Hello, can we please have a new dataset with the errors fixed so we can test the workflow?

**Comment by ghost** [comment]
Hi Targos,

What do you need exactly, I am not sure I understand the request.

**Comment by targos** [comment]
I mean the updated XML files

**Comment by ghost** [comment]
I will go back to our conversion team and request for update. Will keep you informed.

**Comment by ghost** [comment]
Ok, it seems all of those are corrected, the others have hopefully no other issues.

**Comment by targos** [comment]
Ping. I'm still waiting for the updated zip file

**Comment by ghost** [comment]
Hi, you can find them here: https://ufile.io/ag2jz

**Comment by ghost** [comment]
Any news on this ticket, are the files ok now?

**Comment by targos** [comment]
It looks like we have a new issue. The supplementary material used to have the structure as a 2D molfile, but that is not the case anymore.

Example from `molbank-2002-M278.xml`:
```xml
<supplementary-material
  id="molbank-2002-M278-s002"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xlink:href="molbank-2002-M278-s001.mol"
>
	  <label>Supplementary File 2</label>
</supplementary-material>
```

This file is named "molbank-2002-M278-s001.mol" but when I do the request to get it (http://www.mdpi.com/1422-8599/2002/1/M278/s2), I receive an InChI instead.

Is that an expected change?

**Comment by lpatiny** [comment]
Actually the molfile is in the supplementary file 3 but it is not present in the XML
And the supplementary file 2 has an extension '.mol' but is in fact an InCHi which is quite confusing.

![image](https://user-images.githubusercontent.com/1484241/30599208-0ced850c-9d5c-11e7-80ee-405164c1c2a3.png)

**Comment by ghost** [comment]
Hi Luc,

Got this error, I asked our XML conversion team to check and fix tis issue. Is this a single error you found, or thie happens also in other articles?

**Comment by targos** [comment]
It is for almost all articles

**Comment by ghost** [comment]
Hm, I see. Our editors will check and fix this until the end of the month (September). Once done, I will let you know.

**Comment by ghost** [comment]
https://we.tl/RMUwHLbAQ7
The new corrected XML files are ready.

**Comment by targos** [comment]
Thanks. It's better but there are still problems with many articles, especially from 2003.
Also, for all articles from 2016 and 2017, the supplementary materials are not listed anymore in the XML.

<details>
<summary>Problematic files (click to open)</summary>

```
Missing mol2d: molbank-2002-M293
Missing mol2d: molbank-2003-M298
Missing mol2d: molbank-2003-M299
Missing mol2d: molbank-2003-M300
Missing mol2d: molbank-2003-M301
Missing mol2d: molbank-2003-M302
Missing mol2d: molbank-2003-M303
Missing mol2d: molbank-2003-M304
Missing mol2d: molbank-2003-M305
Missing mol2d: molbank-2003-M306
Missing mol2d: molbank-2003-M307
Missing mol2d: molbank-2003-M308
Missing mol2d: molbank-2003-M309
Missing mol2d: molbank-2003-M310
Missing mol2d: molbank-2003-M311
Missing mol2d: molbank-2003-M312
Missing mol2d: molbank-2003-M313
Missing mol2d: molbank-2003-M315
Missing mol2d: molbank-2003-M316
Missing mol2d: molbank-2003-M317
Missing mol2d: molbank-2003-M318
Missing mol2d: molbank-2003-M319
Missing mol2d: molbank-2003-M320
Missing mol2d: molbank-2003-M321
Missing mol2d: molbank-2003-M322
Missing mol2d: molbank-2003-M323
Missing mol2d: molbank-2003-M324
Missing mol2d: molbank-2003-M325
File not found: http://www.mdpi.com/1422-8599/2003/4/M339/s1
File not found: http://www.mdpi.com/1422-8599/2003/4/M339/s3
Missing mol2d: molbank-2003-M339
Missing mol2d: molbank-2003-M347
Missing mol2d: molbank-2003-M348
Missing mol2d: molbank-2004-M359
Missing mol2d: molbank-2004-M360
Missing mol2d: molbank-2006-M466
Missing mol2d: molbank-2007-M527
Missing mol2d: molbank-2007-M536
Missing mol2d: molbank-2008-M565
File not found: http://www.mdpi.com/1422-8599/2008/3/M567/s1
File not found: http://www.mdpi.com/1422-8599/2008/3/M567/s3
Missing mol2d: molbank-2008-M567
Missing mol2d: molbank-2008-M574
Missing mol2d: molbank-2008-M577
Missing mol2d: molbank-2009-M592
Missing mol2d: molbank-2009-M593
Missing mol2d: molbank-2012-M747
Missing mol2d: molbank-2003-M329
Missing mol2d: molbank-2014-M818
Missing mol2d: molbank-2015-M862
Missing mol2d: molbank-2016-M882
Missing mol2d: molbank-2016-M883
Missing mol2d: molbank-2016-M884
Missing mol2d: molbank-2016-M885
Missing mol2d: molbank-2016-M886
Missing mol2d: molbank-2016-M888
Missing mol2d: molbank-2016-M889
Missing mol2d: molbank-2016-M890
Missing mol2d: molbank-2016-M891
Missing mol2d: molbank-2016-M892
Missing mol2d: molbank-2016-M893
Missing mol2d: molbank-2016-M894
Missing mol2d: molbank-2016-M895
Missing mol2d: molbank-2016-M896
Missing mol2d: molbank-2016-M897
Missing mol2d: molbank-2016-M898
Missing mol2d: molbank-2016-M899
Missing mol2d: molbank-2016-M900
Missing mol2d: molbank-2016-M901
Missing mol2d: molbank-2016-M902
Missing mol2d: molbank-2016-M903
Missing mol2d: molbank-2016-M904
Missing mol2d: molbank-2016-M905
Missing mol2d: molbank-2016-M906
Missing mol2d: molbank-2016-M907
Missing mol2d: molbank-2016-M908
Missing mol2d: molbank-2016-M909
Missing mol2d: molbank-2016-M910
Missing mol2d: molbank-2016-M911
Missing mol2d: molbank-2016-M912
Missing mol2d: molbank-2016-M913
Missing mol2d: molbank-2016-M914
Missing mol2d: molbank-2016-M915
Missing mol2d: molbank-2016-M916
Missing mol2d: molbank-2016-M917
Missing mol2d: molbank-2016-M918
Missing mol2d: molbank-2016-M919
Missing mol2d: molbank-2016-M920
Missing mol2d: molbank-2016-M921
Missing mol2d: molbank-2017-M922
Missing mol2d: molbank-2017-M923
Missing mol2d: molbank-2017-M924
Missing mol2d: molbank-2017-M925
Missing mol2d: molbank-2017-M927
Missing mol2d: molbank-2017-M928
Missing mol2d: molbank-2017-M929
Missing mol2d: molbank-2017-M930
Missing mol2d: molbank-2017-M931
Missing mol2d: molbank-2017-M932
Missing mol2d: molbank-2017-M933
Missing mol2d: molbank-2017-M934
Missing mol2d: molbank-2017-M935
Missing mol2d: molbank-2017-M936
Missing mol2d: molbank-2017-M937
Missing mol2d: molbank-2017-M938
Missing mol2d: molbank-2017-M939
Missing mol2d: molbank-2017-M940
Missing mol2d: molbank-2017-M941
Missing mol2d: molbank-2017-M942
Missing mol2d: molbank-2017-M943
Missing mol2d: molbank-2017-M944
Missing mol2d: molbank-2017-M945
Missing mol2d: molbank-2017-M946
Missing mol2d: molbank-2017-M947
Missing mol2d: molbank-2017-M948
Missing mol2d: molbank-2017-M949
Missing mol2d: molbank-2017-M950
Missing mol2d: molbank-2017-M951
Missing mol2d: molbank-2017-M952
Missing mol2d: molbank-2017-M953
Missing mol2d: molbank-2017-M954
Missing mol2d: molbank-2017-M955
Missing mol2d: molbank-2017-M956
Missing mol2d: molbank-2017-M957
Missing mol2d: molbank-2017-M958
```
</details>


For example with M321: http://www.mdpi.com/1422-8599/2003/2/M321

In the article, we have:
- 1: 3D molfile
- 2: inchi (but still with `.mol` extension)
- 3: molfile

In the XML, we have:
- 1: 3D molfile
- 2: molfile
- 3: PDF

```xml
<app id="app1-molbank-2003-M321">
        <title>Supplementary materials</title>
        <supplementary-material id="molbank-2003-M321-s001" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="molbank-2003-M321-s001-mod.mol">
   <label>Supplementary File 1</label>
</supplementary-material>
        <supplementary-material id="molbank-2003-M321-s002" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="molbank-2003-M321-s001.mol">
   <label>Supplementary File 2</label>
</supplementary-material>
<supplementary-material id="molbank-2003-M321-s003" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="molbank-2003-M321-s001.pdf">
   <label>Supplementary File 3</label>
</supplementary-material>
    </app>
```

**Comment by ghost** [comment]
Thanks Michael,

Forwarding this to our production team.

- Kindest regards,

Milos Cuculovic
IT Manager

---
MDPI AG
Postfach, CH-4020 Basel, Switzerland
Office: St. Alban-Anlage 66, 4052 Basel, Switzerland
Tel. +41 61 683 77 35
Fax +41 61 302 89 18
Email: cuculovic@mdpi.com
Skype: milos.cuculovic.mdpi

Disclaimer: The information and files contained in this message are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this message in error, please notify me and delete this message from your system. You may not copy this message in its entirety or in part, or disclose its contents to anyone.

**Comment by ghost** [comment]
Dear All,

We are so sorry for the mistake, I have corrected most of them and the 
revised version has been uploaded.

for all articles from 2016 and 2017, the supplementary materials codes 
have been added in the XML.

but there are some manuscripts cannot find any mistakes or have no 
Supplementary Material on pdf.

it list as follow:

Please check and process it, if there are any problems please kindly 
inform us.

Best,
Ying

Ms. Ying Wang
Production Manager, MDPI AG
MDPI AG Branch Office, Wuhan
Tel.: +86 27 87808658
Fax : +86 27 87612588
E-Mail: ying.wang@mdpi.com

MDPI AG
Postfach, CH-4020 Basel, Switzerland
Office: St. Alban-Anlage 66, 4052 Basel
Tel. +41 61 683 77 34; Fax  +41 61 302 89 18
http://www.mdpi.com/

**Comment by ghost** [comment]
Thanks Ying, the list is attached:

![dmidlknkmphgifeo](https://user-images.githubusercontent.com/4981692/31117629-d8985d0c-a82a-11e7-8f0a-3dca25357f78.png)

@Michael, is all ok now?

**Comment by ghost** [comment]
Hi Targos, are now all the XML files ok in order to implement the rest of the project?

**Comment by targos** [comment]
Hi, I don't know where the last revised version was uploaded. Do you have a link?

**Comment by ghost** [comment]
[Molbank XMLs.zip](https://github.com/cheminfo/molbank/files/1471383/Molbank.XMLs.zip)
Here is the new batch of XMLs

**Comment by targos** [comment]
Thank you. I will write a guide by tomorrow

**Comment by ghost** [comment]
Thanks.
