### ISSUE TITLE
cheminfo.org/flavor/molbank - stuck at the loading screen

### ISSUE THREAD

**Issue by ghost** [cheminfo/molbank#9]
We are trying to view https://www.cheminfo.org/flavor/molbank/index.html, see attached screenshot. The PDF reader is stuck at Loading. Browser used: FirefoxForDevelopers on MAC.

<img width="1920" alt="screen shot 2017-12-18 at 11 50 47" src="https://user-images.githubusercontent.com/4981692/34102563-eae42bc6-e3e9-11e7-9508-c9f2852cded2.png">

**Comment by lpatiny** [comment]
I can not reproduce this problem. Which browser are you using ?

**Comment by ghost** [comment]
FirefoxForDevelopers, bit this seems to work now, a temporary issue maybe?
We can close this ticket for now, will reopen it again if this is aimed to happen again.
